[[glslang]]
arch = "aarch64"
git-tree-sha1 = "1cb6e6316c7810f9ac1915df295fbec573033136"
os = "macos"

    [[glslang.download]]
    sha256 = "a0914414cfc6c6780891f10690a81f03b3ae0743b6280d05fd815c0f8f6c2d80"
    url = "https://github.com/JuliaBinaryWrappers/glslang_jll.jl/releases/download/glslang-v11.7.0+0/glslang.v11.7.0.aarch64-apple-darwin.tar.gz"
[[glslang]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e15ac7673d616c384ee41d69dec1faa5f51063c2"
libc = "glibc"
os = "linux"

    [[glslang.download]]
    sha256 = "63e20c91cfba63951ca7e53159f756c1866b6c16c0c7497c70e562c8245bc85c"
    url = "https://github.com/JuliaBinaryWrappers/glslang_jll.jl/releases/download/glslang-v11.7.0+0/glslang.v11.7.0.aarch64-linux-gnu-cxx03.tar.gz"
[[glslang]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c22551b8ecdc03ed7a734547ff1c6cb6c531705d"
libc = "glibc"
os = "linux"

    [[glslang.download]]
    sha256 = "7efe26553d12598582552296846b466e45a36bfd3a6f03c07b79cd5263dafd5c"
    url = "https://github.com/JuliaBinaryWrappers/glslang_jll.jl/releases/download/glslang-v11.7.0+0/glslang.v11.7.0.aarch64-linux-gnu-cxx11.tar.gz"
[[glslang]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ce01e635f0ff1b53505bfa2a0d6161b4dc0f2047"
libc = "musl"
os = "linux"

    [[glslang.download]]
    sha256 = "6427d77a4101f4dafb54ea0755cb92b8b809d7a8a8c3f2dfb493d209a724cc1e"
    url = "https://github.com/JuliaBinaryWrappers/glslang_jll.jl/releases/download/glslang-v11.7.0+0/glslang.v11.7.0.aarch64-linux-musl-cxx03.tar.gz"
[[glslang]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b3c1be368827d7dae6051489b50d4cb4f45b6de2"
libc = "musl"
os = "linux"

    [[glslang.download]]
    sha256 = "8a6d106de7201209b63948400fb5fcd5c0b8d98b665be1753b1e7b852551ec04"
    url = "https://github.com/JuliaBinaryWrappers/glslang_jll.jl/releases/download/glslang-v11.7.0+0/glslang.v11.7.0.aarch64-linux-musl-cxx11.tar.gz"
[[glslang]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d2172c7739048d46fced23b790a19796e93bac79"
libc = "glibc"
os = "linux"

    [[glslang.download]]
    sha256 = "1c0897f51d7ec792c18023a540f3b3b6514dd867604a13cd2b719c5b2d7c5f7d"
    url = "https://github.com/JuliaBinaryWrappers/glslang_jll.jl/releases/download/glslang-v11.7.0+0/glslang.v11.7.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[glslang]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "15d47454aa2105a63435207371c512acab92ec4c"
libc = "glibc"
os = "linux"

    [[glslang.download]]
    sha256 = "ae09b7aa15035416ae52ebab42b4f6286bd4931d7ccbc28f08f5045a5bccf798"
    url = "https://github.com/JuliaBinaryWrappers/glslang_jll.jl/releases/download/glslang-v11.7.0+0/glslang.v11.7.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[glslang]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6b635396fa4cae164a4585d8d42a778f40baf149"
libc = "musl"
os = "linux"

    [[glslang.download]]
    sha256 = "bfe4bc630d0a830232208c69a0eaca312c2306d8c3f180c327cfaac315c828ea"
    url = "https://github.com/JuliaBinaryWrappers/glslang_jll.jl/releases/download/glslang-v11.7.0+0/glslang.v11.7.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[glslang]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e50cdcaffc4693dda0ef5f63e4ebc27ab97458e4"
libc = "musl"
os = "linux"

    [[glslang.download]]
    sha256 = "35ce942cdf063e263e71e9a3e6e23aaa5e1413449bb7747c62dd91f3aed28c38"
    url = "https://github.com/JuliaBinaryWrappers/glslang_jll.jl/releases/download/glslang-v11.7.0+0/glslang.v11.7.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[glslang]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "27f1df246926d5a194e8a6e7c3f4e40049c3d635"
libc = "glibc"
os = "linux"

    [[glslang.download]]
    sha256 = "8316f3d01a5e51e8af623a1c2fe2b3dc45629c7d4758f09572b02510e47b6baa"
    url = "https://github.com/JuliaBinaryWrappers/glslang_jll.jl/releases/download/glslang-v11.7.0+0/glslang.v11.7.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[glslang]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "50206cd3e3144a8cd23fc32bfa6ecd3bd0ed4a3a"
libc = "glibc"
os = "linux"

    [[glslang.download]]
    sha256 = "6d6641ae19d9ae2a5d0c4ea426d1938053a90b322f2f0af79bba1943b3e90e96"
    url = "https://github.com/JuliaBinaryWrappers/glslang_jll.jl/releases/download/glslang-v11.7.0+0/glslang.v11.7.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[glslang]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9f0f818188d92615ee9195bab825d8bec64f6c5f"
libc = "musl"
os = "linux"

    [[glslang.download]]
    sha256 = "c1ca5272684faaf11706da139efb6e1e26f7ea43ebff2df2bf4f36cfc85fc4ca"
    url = "https://github.com/JuliaBinaryWrappers/glslang_jll.jl/releases/download/glslang-v11.7.0+0/glslang.v11.7.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[glslang]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5a0f29be97062a9d25393b0e5c680ccf76de48d9"
libc = "musl"
os = "linux"

    [[glslang.download]]
    sha256 = "94a8b049e37302244a373cc8b7f2ad47b31da4ec3adb4a1f2591b9c5e75197e6"
    url = "https://github.com/JuliaBinaryWrappers/glslang_jll.jl/releases/download/glslang-v11.7.0+0/glslang.v11.7.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[glslang]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c012e2004f9622b30a2b58364e532d855c9e66aa"
libc = "glibc"
os = "linux"

    [[glslang.download]]
    sha256 = "e2ad077280051d6cc0188b007ab44153dbe6cb2f0689ff32348389397355a00e"
    url = "https://github.com/JuliaBinaryWrappers/glslang_jll.jl/releases/download/glslang-v11.7.0+0/glslang.v11.7.0.i686-linux-gnu-cxx03.tar.gz"
[[glslang]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6c34c3b09cb116d47efea1b99a11622f252da2f1"
libc = "glibc"
os = "linux"

    [[glslang.download]]
    sha256 = "f6c250ed4d7300639e5906350fdca5a62322afad02bb9eb321d5c81f47f35c41"
    url = "https://github.com/JuliaBinaryWrappers/glslang_jll.jl/releases/download/glslang-v11.7.0+0/glslang.v11.7.0.i686-linux-gnu-cxx11.tar.gz"
[[glslang]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9642feb660b77682a4ad327c82122a6e4afaaf00"
libc = "musl"
os = "linux"

    [[glslang.download]]
    sha256 = "86ddf6e83defdee57f7419233cad1a73c6bcb7f919547b653a58737f749db109"
    url = "https://github.com/JuliaBinaryWrappers/glslang_jll.jl/releases/download/glslang-v11.7.0+0/glslang.v11.7.0.i686-linux-musl-cxx03.tar.gz"
[[glslang]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f66c16d636577756f40404221688b15446af8d88"
libc = "musl"
os = "linux"

    [[glslang.download]]
    sha256 = "187a3c1e6d1367ec25cbcc53a6da3f7dfce27c670560f20ae57764d6af2de0eb"
    url = "https://github.com/JuliaBinaryWrappers/glslang_jll.jl/releases/download/glslang-v11.7.0+0/glslang.v11.7.0.i686-linux-musl-cxx11.tar.gz"
[[glslang]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "22978899a7d56876b6774b6d3167216671b74fa4"
os = "windows"

    [[glslang.download]]
    sha256 = "ebc025e0b619771f47e7f7b7f056db5e17c6355a49749df73fb497cf5469823d"
    url = "https://github.com/JuliaBinaryWrappers/glslang_jll.jl/releases/download/glslang-v11.7.0+0/glslang.v11.7.0.i686-w64-mingw32-cxx03.tar.gz"
[[glslang]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "72a4e5915bcb4c42f5305f6c8c58ad538d7055a6"
os = "windows"

    [[glslang.download]]
    sha256 = "1c6ce0aee5576b3791e03f28ed5a1fb4c9b949b58ece9931daf36b89a9d3d07c"
    url = "https://github.com/JuliaBinaryWrappers/glslang_jll.jl/releases/download/glslang-v11.7.0+0/glslang.v11.7.0.i686-w64-mingw32-cxx11.tar.gz"
[[glslang]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6920fa88b5dffa2c89c9077f2d78890430b9de9d"
libc = "glibc"
os = "linux"

    [[glslang.download]]
    sha256 = "f5d041e513f77e95a494f1694efa6fe0caca3b3b1f8ede84754166122e0b2fd9"
    url = "https://github.com/JuliaBinaryWrappers/glslang_jll.jl/releases/download/glslang-v11.7.0+0/glslang.v11.7.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[glslang]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a499e425a7416ce90b8f8cee36c995fd4aaf1469"
libc = "glibc"
os = "linux"

    [[glslang.download]]
    sha256 = "5670474f16544c32a91e77696417d2c80433f6585d5b24d983f1af5b1adde787"
    url = "https://github.com/JuliaBinaryWrappers/glslang_jll.jl/releases/download/glslang-v11.7.0+0/glslang.v11.7.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[glslang]]
arch = "x86_64"
git-tree-sha1 = "9a69cfee725f18d3fe399bf591b9e4428fcd69d6"
os = "macos"

    [[glslang.download]]
    sha256 = "e054a5a02d2b8831c7fad744718c7f7615d431bca36fb8409bcfa0d19d682724"
    url = "https://github.com/JuliaBinaryWrappers/glslang_jll.jl/releases/download/glslang-v11.7.0+0/glslang.v11.7.0.x86_64-apple-darwin.tar.gz"
[[glslang]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7b1821fde36f0b1669f24d5febc7beef831736dc"
libc = "glibc"
os = "linux"

    [[glslang.download]]
    sha256 = "76798494575dbe6706052a20bee76eefe4fa162609483aa2792ed66d1fc6bf55"
    url = "https://github.com/JuliaBinaryWrappers/glslang_jll.jl/releases/download/glslang-v11.7.0+0/glslang.v11.7.0.x86_64-linux-gnu-cxx03.tar.gz"
[[glslang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f1fa93f41410326ba4ca250dbf71306ccc966830"
libc = "glibc"
os = "linux"

    [[glslang.download]]
    sha256 = "10ec3e547fca0802da33fe97f6cb7ff2c52b3348aa7d6917dbc544e57081b3ad"
    url = "https://github.com/JuliaBinaryWrappers/glslang_jll.jl/releases/download/glslang-v11.7.0+0/glslang.v11.7.0.x86_64-linux-gnu-cxx11.tar.gz"
[[glslang]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3ce382db2925cc743b0d60eb4b5fbee328008e79"
libc = "musl"
os = "linux"

    [[glslang.download]]
    sha256 = "94f6974795d2d35b6fb026ed063dd0d324171d52b92bbb12ea789c398bbb5acf"
    url = "https://github.com/JuliaBinaryWrappers/glslang_jll.jl/releases/download/glslang-v11.7.0+0/glslang.v11.7.0.x86_64-linux-musl-cxx03.tar.gz"
[[glslang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "25e6c39d9a5813999eb16fbadc9753e508f5e278"
libc = "musl"
os = "linux"

    [[glslang.download]]
    sha256 = "e93326b522348b13e834c13e112eece7254f8ca2d29b8f39964a7ad6909c373c"
    url = "https://github.com/JuliaBinaryWrappers/glslang_jll.jl/releases/download/glslang-v11.7.0+0/glslang.v11.7.0.x86_64-linux-musl-cxx11.tar.gz"
[[glslang]]
arch = "x86_64"
git-tree-sha1 = "e8a8d1218843c148f1c1911906e92e23a902e059"
os = "freebsd"

    [[glslang.download]]
    sha256 = "f5337f1c91206e1bfa57a281fefea42c625c3e977f3f2bad7ea7c054c46d6520"
    url = "https://github.com/JuliaBinaryWrappers/glslang_jll.jl/releases/download/glslang-v11.7.0+0/glslang.v11.7.0.x86_64-unknown-freebsd.tar.gz"
[[glslang]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0d53d0e18102ffc5f7d397eeadec7b4d72f55db2"
os = "windows"

    [[glslang.download]]
    sha256 = "8f34a78006955a7569b6b2243e97447695038d136e5c41e57d19f905ce287ae2"
    url = "https://github.com/JuliaBinaryWrappers/glslang_jll.jl/releases/download/glslang-v11.7.0+0/glslang.v11.7.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[glslang]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "46d47f956e78e0ea16c4661183b351bb6bb768d5"
os = "windows"

    [[glslang.download]]
    sha256 = "ca57230af82d97e921f74d36908ef5b4bd327ea926b79208205ef255b9863d1b"
    url = "https://github.com/JuliaBinaryWrappers/glslang_jll.jl/releases/download/glslang-v11.7.0+0/glslang.v11.7.0.x86_64-w64-mingw32-cxx11.tar.gz"
