# Autogenerated wrapper script for glslang_jll for i686-w64-mingw32-cxx11
export glslangValidator

JLLWrappers.@generate_wrapper_header("glslang")
JLLWrappers.@declare_executable_product(glslangValidator)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        glslangValidator,
        "bin\\glslangValidator.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
